import { Component, OnInit } from '@angular/core';
import {MatDialog, MatDialogRef} from "@angular/material/dialog";
import {MetricForm} from "../table-metrics/table-metrics.component";

export interface PeriodicElement {
  name: string;
  description: string;
  references: string;
}

const ELEMENT_DATA: PeriodicElement[] = [

  {name: 'Accountability', description: 'Defined as the extent to which an entity’s action may be traced back to it exclusively [1,13]. Accountability can be seen as a combination of the following design properties: polymorphism, coupling, cohesion, and hierarchies', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="https://link.springer.com/article/10.1007/s13319-018-0183-x" target="_blank" rel="noopener noreferrer">[13]</a>'},
  {name: 'Adaptability', description: 'Defined as the degree to which a system may effectively and efficiently be adapted to handle changes in the system or its operational environment [1,47]', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="https://dl.acm.org/doi/abs/10.1016/j.jss.2013.07.053" target="_blank" rel="noopener noreferrer">[47]</a>'},
  {name: 'Analyzability', description: 'Defined as the degree of efficacy and efficiency with which it is possible to assess the influence of an intended change to system components, or to diagnose for reasons of failures, or to identify components to be modified [1,12,14]', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="http://www.inass.org/2018/2018083109.pdf\n" target="_blank" rel="noopener noreferrer">[12]</a><a href="https://dl.acm.org/doi/10.1145/2980258.2980459\n" target="_blank" rel="noopener noreferrer">[14]</a>'},
  {name: 'Authenticity', description: 'Defined as the degree to which the asserted identity of a subject or resource may be proven [1,13]. Authenticity is seen as a combination of the following design properties: inheritance, complexity, polymorphism, and cohesion', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="https://link.springer.com/article/10.1007/s13319-018-0183-x" target="_blank" rel="noopener noreferrer">[13]</a>'},
  {name: 'Availability', description: 'Defined as the extent to which a system or component is operational and available when required for use [1,17,19,22,29,43,44,48]', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="https://www.scitepress.org/papers/2014/50037/50037.pdf" target="_blank" rel="noopener noreferrer">[17]</a><a href="https://dl.acm.org/doi/abs/10.1504/IJCAT.2016.080489" target="_blank" rel="noopener noreferrer">[19]</a><a href="https://ieeexplore.ieee.org/document/8754186" target="_blank" rel="noopener noreferrer">[22]</a><a href="https://dl.acm.org/doi/abs/10.1016/j.infsof.2021.106713" target="_blank" rel="noopener noreferrer">[29]</a><a href="https://www.sciencedirect.com/science/article/pii/S1877050917300510" target="_blank" rel="noopener noreferrer">[43]</a><a href="https://www.sciencedirect.com/science/article/pii/S1877705817301042" target="_blank" rel="noopener noreferrer">[44]</a><a href="https://link.springer.com/article/10.1007/s00607-017-0568-3" target="_blank" rel="noopener noreferrer">[48]</a>'},
  {name: 'Clearness', description: 'Defined as the extent to which the documentation is appropriate for the intended audience [50]. It concerns about the possibility of the developer to successfully implement the system using the architecture model', references: '<a href="https://dl.acm.org/doi/10.1145/2578128.2578226" target="_blank" rel="noopener noreferrer">[50]</a>'},
  {name: 'Cohesion', description: 'Defined as the degree to which the components of a module are related [56]', references: '<a href="https://dl.acm.org/doi/10.1145/2752489.2752496" target="_blank" rel="noopener noreferrer">[56]</a>'},
  {name: 'Completeness', description: 'Defined as the coverage of quality aspects and requirements in the architectural model [50]', references: '<a href="https://dl.acm.org/doi/10.1145/2578128.2578226" target="_blank" rel="noopener noreferrer">[50]</a>'},
  {name: 'Complexity', description: 'Defined as the degree to which a system or component has a design or implementation that is difficult to understand and verify [13]. This QA is also cited in other works [23,36,44]', references: '<a href="https://link.springer.com/article/10.1007/s13319-018-0183-x" target="_blank" rel="noopener noreferrer">[13]</a><a href="https://www.researchgate.net/publication/339902830_Towards_Metrics_for_Analyzing_System_Architectures_Modeled_with_EAST-ADL" target="_blank" rel="noopener noreferrer">[23]</a><a href="https://link.springer.com/article/10.1007/s10462-021-09974-2" target="_blank" rel="noopener noreferrer">[36]</a><a href="https://www.sciencedirect.com/science/article/pii/S1877705817301042" target="_blank" rel="noopener noreferrer">[44]</a>'},
  {name: 'Confidentiality', description: 'Defined as the extent to which the system’s prototype ensures that data is only available to those who are authorized [1,13]', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="https://link.springer.com/article/10.1007/s13319-018-0183-x" target="_blank" rel="noopener noreferrer">[13]</a>'},
  {name: 'Consistency', description: 'Defined as the presence of conflicting choices or inconsistencies between architecture model and design decisions [50]', references: '<a href="https://dl.acm.org/doi/10.1145/2578128.2578226" target="_blank" rel="noopener noreferrer">[50]</a>'},
  {name: 'Context Awareness', description: 'Defined as the ability to collect information about the operating context, e.g. information of the user or of a car, such as information coming from GPS or proximity sensors [27]', references: '<a href="https://dl.acm.org/doi/abs/10.1145/2602458.2602460" target="_blank" rel="noopener noreferrer">[27]</a>'},
  {name: 'Correctness', description: 'Defined as a quality aspect deciding whether every design decision follows from a requirement [50]', references: '<a href="https://dl.acm.org/doi/10.1145/2578128.2578226" target="_blank" rel="noopener noreferrer">[50]</a>'},
  {name: 'Discoverability', description: 'Defined as the degree to which the interfaces provided by a service are discoverable [3]. This is used in relation to the microservice architectural style [3]', references: '<a href="https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7965739" target="_blank" rel="noopener noreferrer">[3]</a>'},
  {name: 'Evolvability', description: 'Defined as the ability of software products to evolve in order to continue to provide cost-effective service to customers [59]', references: '<a href="https://www.researchgate.net/publication/336257409_Analyzing_Software_Architecture_Evolvability_Based_on_Multiple_Architectural_Attributes_Measurements" target="_blank" rel="noopener noreferrer">[59]</a>'},
  {name: 'Extensibility', description: 'Defines whether a software architecture allows extensions to be implemented to extend the system with new capabilities and features with minimum impact on the present software architecture [59] This QA is often referred as Extendability or Extensibility [19,29,43,44,59]', references: '<a href="https://dl.acm.org/doi/abs/10.1504/IJCAT.2016.080489" target="_blank" rel="noopener noreferrer">[19]</a><a href="https://dl.acm.org/doi/abs/10.1016/j.infsof.2021.106713" target="_blank" rel="noopener noreferrer">[29]</a><a href="https://www.sciencedirect.com/science/article/pii/S1877050917300510" target="_blank" rel="noopener noreferrer">[43]</a><a href="https://www.sciencedirect.com/science/article/pii/S1877705817301042" target="_blank" rel="noopener noreferrer">[44]</a><a href="https://www.researchgate.net/publication/336257409_Analyzing_Software_Architecture_Evolvability_Based_on_Multiple_Architectural_Attributes_Measurements" target="_blank" rel="noopener noreferrer">[59]</a>'},
  {name: 'Flexibility', description: 'The ability to change the design, and then the architecture, to introduce characteristics functionally related to existing functions [44,51]', references: '<a href="https://www.sciencedirect.com/science/article/pii/S1877705817301042" target="_blank" rel="noopener noreferrer">[44]</a><a href="https://dl.acm.org/doi/abs/10.1145/2642803.2642817" target="_blank" rel="noopener noreferrer">[51]</a>'},
  {name: 'Functionality', description: 'Defined as the ability of the software product to provide functional requirements in a specific situation [41]', references: '<a href="https://link.springer.com/article/10.1007/s10115-020-01496-7" target="_blank" rel="noopener noreferrer">[41]</a>'},
  {name: 'Integrity', description: 'Defined as the degree to which a system or component protects software modules or data from unauthorized access or change [1,13]', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="https://link.springer.com/article/10.1007/s13319-018-0183-x" target="_blank" rel="noopener noreferrer">[13]</a>'},
  {name: 'Interoperability', description: 'Defined as the degree to which two or more systems or components can exchange information and use the exchanged information [1,19,43,44]', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="https://dl.acm.org/doi/abs/10.1504/IJCAT.2016.080489" target="_blank" rel="noopener noreferrer">[19]</a><a href="https://www.sciencedirect.com/science/article/pii/S1877050917300510" target="_blank" rel="noopener noreferrer">[43]</a><a href="https://www.sciencedirect.com/science/article/pii/S1877705817301042" target="_blank" rel="noopener noreferrer">[44]</a>'},
  {name: 'Maintainability', description: 'Defined as the ease and efficacy with which a system can be adjusted to improve, correct, or adapt to changes in the environment and requirements [1,3,12,14,17,21,23,29,33,39,41,54,56,58,61]', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="https://ieeexplore.ieee.org/document/7965739" target="_blank" rel="noopener noreferrer">[3]</a><a href="http://www.inass.org/2018/2018083109.pdf\n" target="_blank" rel="noopener noreferrer">[12]</a><a href="https://dl.acm.org/doi/10.1145/2980258.2980459\n" target="_blank" rel="noopener noreferrer">[14]</a><a href="https://www.scitepress.org/papers/2014/50037/50037.pdf" target="_blank" rel="noopener noreferrer">[17]</a><a href="https://www.sciencedirect.com/science/article/abs/pii/S0164121212003330 " target="_blank" rel="noopener noreferrer">[21]</a><a href="https://www.researchgate.net/publication/339902830_Towards_Metrics_for_Analyzing_System_Architectures_Modeled_with_EAST-ADL" target="_blank" rel="noopener noreferrer">[23]</a><a href="https://dl.acm.org/doi/abs/10.1016/j.infsof.2021.106713" target="_blank" rel="noopener noreferrer">[29]</a><a href="https://dl.acm.org/doi/10.1145/2529998" target="_blank" rel="noopener noreferrer">[33]</a><a href="https://ieeexplore.ieee.org/document/7886929" target="_blank" rel="noopener noreferrer">[39]</a><a href="https://link.springer.com/article/10.1007/s10115-020-01496-7" target="_blank" rel="noopener noreferrer">[41]</a><a href="https://ieeexplore.ieee.org/document/8754186" target="_blank" rel="noopener noreferrer">[54]</a><a href="https://dl.acm.org/doi/10.1145/2752489.2752496" target="_blank" rel="noopener noreferrer">[56]</a><a href="https://ieeexplore.ieee.org/document/8286359" target="_blank" rel="noopener noreferrer">[58]</a><a href="https://www.sciencedirect.com/science/article/pii/S0164121221002089" target="_blank" rel="noopener noreferrer">[61]</a>'},
  {name: 'Maturity', description: 'Defined as the degree to which a component or system meets the requirements for reliability [1,43,44]', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="https://www.sciencedirect.com/science/article/pii/S1877050917300510" target="_blank" rel="noopener noreferrer">[43]</a><a href="https://www.sciencedirect.com/science/article/pii/S1877705817301042" target="_blank" rel="noopener noreferrer">[44]</a>'},
  {name: 'Modifiability', description: 'Defined as the extent to which a system may be updated effectively and efficiently without introducing flaws or lowering the product quality [1,12,14,22]', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="http://www.inass.org/2018/2018083109.pdf\n" target="_blank" rel="noopener noreferrer">[12]</a><a href="https://dl.acm.org/doi/10.1145/2980258.2980459\n" target="_blank" rel="noopener noreferrer">[14]</a><a href="https://ieeexplore.ieee.org/document/8754186" target="_blank" rel="noopener noreferrer">[22]</a>'},
  {name: 'Modularity', description: 'Defined as the degree to which a system is made out of discrete components, so that changing one has minor effect on the others [1,12,14,44]', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="http://www.inass.org/2018/2018083109.pdf\n" target="_blank" rel="noopener noreferrer">[12]</a><a href="https://dl.acm.org/doi/10.1145/2980258.2980459\n" target="_blank" rel="noopener noreferrer">[14]</a><a href="https://www.sciencedirect.com/science/article/pii/S1877705817301042" target="_blank" rel="noopener noreferrer">[44]</a>'},
  {name: 'Non-Repudiation', description: 'The degree to which actions or events may be demonstrated to have occurred such that they cannot be repudiated in the future [1,13]. It is seen as a combination of the following design properties: design size, cohesion, complexity, and encapsulation', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="https://link.springer.com/article/10.1007/s13319-018-0183-x" target="_blank" rel="noopener noreferrer">[13]</a>'},
  {name: 'Performance', description: 'Defined as the degree to which a system or component accomplishes its designated functions within given constraints, such as speed, accuracy, or memory usage [37]. This QA is used in various other works [18,19,22,29,33,36,41,49]', references: '<a href="https://ieeexplore.ieee.org/document/7320338" target="_blank" rel="noopener noreferrer">[18]</a><a href="https://dl.acm.org/doi/abs/10.1504/IJCAT.2016.080489" target="_blank" rel="noopener noreferrer">[19]</a><a href="https://ieeexplore.ieee.org/document/8754186" target="_blank" rel="noopener noreferrer">[22]</a><a href="https://dl.acm.org/doi/abs/10.1016/j.infsof.2021.106713" target="_blank" rel="noopener noreferrer">[29]</a><a href="https://dl.acm.org/doi/10.1145/2529998" target="_blank" rel="noopener noreferrer">[33]</a><a href="https://link.springer.com/article/10.1007/s10462-021-09974-2" target="_blank" rel="noopener noreferrer">[36]</a><a href="https://www.researchgate.net/publication/200622064_Software_Architecture_Evaluation_Methods_for_Performance_Maintainability_Testability_and_Portability/link/02e7e5280e0f4b4283000000/download" target="_blank" rel="noopener noreferrer">[37]</a><a href="https://link.springer.com/article/10.1007/s10115-020-01496-7" target="_blank" rel="noopener noreferrer">[41]</a><a href="https://link.springer.com/chapter/10.1007/978-3-319-24644-4_3" target="_blank" rel="noopener noreferrer">[49]</a>'},
  {name: 'Portability', description: 'The degree to which a system or component may be transferred effectively and efficiently from one hardware, software, or other operational or usage environment to another [1,22,41,56]', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="https://ieeexplore.ieee.org/document/8754186" target="_blank" rel="noopener noreferrer">[22]</a><a href="https://link.springer.com/article/10.1007/s10115-020-01496-7" target="_blank" rel="noopener noreferrer">[41]</a><a href="https://dl.acm.org/doi/10.1145/2752489.2752496" target="_blank" rel="noopener noreferrer">[56]</a>'},
  {name: 'Reliability', description: 'Defined as the extent to which a system or component executes specified functions for a set amount of time under given conditions [1,3,19,21,24,38,41,48,49,58]', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="https://ieeexplore.ieee.org/document/7965739" target="_blank" rel="noopener noreferrer">[3]</a><a href="https://dl.acm.org/doi/abs/10.1504/IJCAT.2016.080489" target="_blank" rel="noopener noreferrer">[19]</a><a href="https://www.sciencedirect.com/science/article/abs/pii/S0164121212003330 " target="_blank" rel="noopener noreferrer">[21]</a><a href="https://ieeexplore.ieee.org/abstract/document/6542601" target="_blank" rel="noopener noreferrer">[24]</a><a href="https://dl.acm.org/doi/10.1145/2000259.2000275" target="_blank" rel="noopener noreferrer">[38]</a><a href="https://link.springer.com/article/10.1007/s10115-020-01496-7" target="_blank" rel="noopener noreferrer">[41]</a><a href="https://link.springer.com/article/10.1007/s00607-017-0568-3" target="_blank" rel="noopener noreferrer">[48]</a><a href="https://link.springer.com/chapter/10.1007/978-3-319-24644-4_3" target="_blank" rel="noopener noreferrer">[49]</a><a href="https://ieeexplore.ieee.org/document/8286359" target="_blank" rel="noopener noreferrer">[58]</a>'},
  {name: 'Responsibility', description: 'Defined as the ability of a system to continue to operate under a predefined conditions [43,44]', references: '<a href="https://www.sciencedirect.com/science/article/pii/S1877050917300510" target="_blank" rel="noopener noreferrer">[43]</a><a href="https://www.sciencedirect.com/science/article/pii/S1877705817301042" target="_blank" rel="noopener noreferrer">[44]</a>'},
  {name: 'Reusability', description: 'The extent to which a component can be reused during design and implementation [1, 12, 14, 22]', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="http://www.inass.org/2018/2018083109.pdf\n" target="_blank" rel="noopener noreferrer">[12]</a><a href="https://dl.acm.org/doi/10.1145/2980258.2980459\n" target="_blank" rel="noopener noreferrer">[14]</a><a href="https://ieeexplore.ieee.org/document/8754186" target="_blank" rel="noopener noreferrer">[22]</a>'},
  {name: 'Robustness', description: 'Defined as the ability to cope with faults to ensure that the faults created inside the system during the execution of modifications do not have a significant impact on other parts of the system [21]', references: '<a href="https://www.sciencedirect.com/science/article/abs/pii/S0164121212003330 " target="_blank" rel="noopener noreferrer">[21]</a>'},
  {name: 'Simplicity', description: 'Defined as the ease and lack of complexity in the benefit to the user of a function provided in the software architecture [6,44]', references: '<a href="https://www.researchgate.net/publication/315549486_Risk_Thinking_for_Cloud-Based_Application_Services" target="_blank" rel="noopener noreferrer">[6]</a><a href="https://www.sciencedirect.com/science/article/pii/S1877705817301042" target="_blank" rel="noopener noreferrer">[44]</a>'},
  {name: 'Scalability', description: 'Defined as the ability of software architectures to be easily scaled [43,44]', references: '<a href="https://www.sciencedirect.com/science/article/pii/S1877050917300510" target="_blank" rel="noopener noreferrer">[43]</a><a href="https://www.sciencedirect.com/science/article/pii/S1877705817301042" target="_blank" rel="noopener noreferrer">[44]</a>'},
  {name: 'Security', description: 'Defined as the degree to which a system safeguards information and data and gives access to data according to levels of authorization [1,13,19,22,27,49]', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="https://link.springer.com/article/10.1007/s13319-018-0183-x" target="_blank" rel="noopener noreferrer">[13]</a><a href="https://dl.acm.org/doi/abs/10.1504/IJCAT.2016.080489" target="_blank" rel="noopener noreferrer">[19]</a><a href="https://ieeexplore.ieee.org/document/8754186" target="_blank" rel="noopener noreferrer">[22]</a><a href="https://dl.acm.org/doi/abs/10.1145/2602458.2602460" target="_blank" rel="noopener noreferrer">[27]</a><a href="https://link.springer.com/chapter/10.1007/978-3-319-24644-4_3" target="_blank" rel="noopener noreferrer">[49]</a>'},
  {name: 'Stability', description: 'Defined as the change resistance and the ability to bounce back from perturbations [5]', references: '<a href="https://www.sciencedirect.com/science/article/abs/pii/S0164121217301620" target="_blank" rel="noopener noreferrer">[5]</a>'},
  {name: 'Suitability', description: 'Degree to which a system provides functions that meet defined needs when used under specific conditions [1,23,43,44]', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="https://www.researchgate.net/publication/339902830_Towards_Metrics_for_Analyzing_System_Architectures_Modeled_with_EAST-ADL" target="_blank" rel="noopener noreferrer">[23]</a><a href="https://www.sciencedirect.com/science/article/pii/S1877050917300510" target="_blank" rel="noopener noreferrer">[43]</a><a href="https://www.sciencedirect.com/science/article/pii/S1877705817301042" target="_blank" rel="noopener noreferrer">[44]</a>'},
  {name: 'Sustainability', description: 'Defined as the architecture’s ability to accept changes in requirements, environment, technologies, business strategies, and goals [28,57]', references: '<a href="https://dl.acm.org/doi/abs/10.1007/s00607-016-0502-0" target="_blank" rel="noopener noreferrer">[28]</a><a href="https://www.sciencedirect.com/science/article/abs/pii/S0164121217303072" target="_blank" rel="noopener noreferrer">[57]</a>'},
  {name: 'Testability', description: 'Defined as the degree of efficacy and efficiency with which test criteria for a system or component [1,12,14,22,33,56,59]', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="http://www.inass.org/2018/2018083109.pdf\n" target="_blank" rel="noopener noreferrer">[12]</a><a href="https://dl.acm.org/doi/10.1145/2980258.2980459\n" target="_blank" rel="noopener noreferrer">[14]</a><a href="https://ieeexplore.ieee.org/document/8754186" target="_blank" rel="noopener noreferrer">[22]</a><a href="https://dl.acm.org/doi/10.1145/2529998" target="_blank" rel="noopener noreferrer">[33]</a><a href="https://dl.acm.org/doi/10.1145/2752489.2752496" target="_blank" rel="noopener noreferrer">[56]</a><a href="https://www.researchgate.net/publication/336257409_Analyzing_Software_Architecture_Evolvability_Based_on_Multiple_Architectural_Attributes_Measurements" target="_blank" rel="noopener noreferrer">[59]</a>'},
  {name: 'Understandability', description: 'Defined as the degree to which users can recognize whether a system is suitable for their needs [1,20,59]. This QA is often referred as “appropriateness recognizability”', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="https://dl.acm.org/doi/abs/10.1109/ASWEC.2014.17" target="_blank" rel="noopener noreferrer">[20]</a><a href="https://www.researchgate.net/publication/336257409_Analyzing_Software_Architecture_Evolvability_Based_on_Multiple_Architectural_Attributes_Measurements" target="_blank" rel="noopener noreferrer">[59]</a>'},
  {name: 'Usability', description: 'Defined as the extent to which a system or component may be utilized by specific users to achieve specific goals with efficiency, effectiveness, and satisfaction in a specific usage environments [1,22,27,41]', references: '<a href="https://www.iso.org/standard/35733.html" target="_blank" rel="noopener noreferrer">[1]</a><a href="https://ieeexplore.ieee.org/document/8754186" target="_blank" rel="noopener noreferrer">[22]</a><a href="https://dl.acm.org/doi/abs/10.1145/2602458.2602460" target="_blank" rel="noopener noreferrer">[27]</a><a href="https://link.springer.com/article/10.1007/s10115-020-01496-7" target="_blank" rel="noopener noreferrer">[41]</a>'},
  // <a href="https://www.sciencedirect.com/science/article/abs/pii/S0164121217303072" target="_blank" rel="noopener noreferrer">[57]</a>

];


@Component({
  selector: 'app-table-attributes',
  templateUrl: './table-attributes.component.html',
  styleUrls: ['./table-attributes.component.css']
})
export class TableAttributesComponent implements OnInit {

  constructor(public dialog: MatDialog) { }

  displayedColumns: string[] = ['name', 'description', 'references'];

  dataSource = ELEMENT_DATA;

  ngOnInit(): void {
  }
  openDialogAttribute(): void {
    const dialogRef = this.dialog.open(AttributeForm, {
    });
    dialogRef.afterClosed().subscribe(result => {
      console.log('The dialog was closed');
    });
  }

}
@Component({
  selector: 'attribute-form',
  templateUrl: 'attribute-form.html',
})
export class AttributeForm {
  constructor(
    public dialogRef: MatDialogRef<MetricForm>
  ) {}
}
